== Innovate Everywhere Recipes

* Clone the repo and open recipes.adoc locally in a browser that supports
  AsciiDoc or in another tool such as asciidoctor

* The GitHub preview of the in-development recipes is at
<<recipes.adoc#>>.

=== Contributing

Want to help? We love to hear that! Below are a few hints to guide you.

==== Writing

These release notes are written in the AsciiDoc (`*.adoc`) format. For some
great AsciiDoc documentation, see https://asciidoctor.org/docs/asciidoc-writers-guide/.

Viewing asciidoc is most easily done via a plugin to Chrome such as
https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia

Add your recipe under recipes/<recipe-type> ... desserts go under recipes/desserts for example

Images associated with the recipe should be added under the images folder at the top level, then
inside a sub-folder with the recipe name

Asciidoctor can be installed for Leap 15.2 at https://software.opensuse.org/package/rubygem-asciidoctor
Other distributions can be found at https://asciidoctor.org/#a-linux-package-managers

After installing asciidoctor, run the build using ./docbuild.sh 
The output of the build will be build/recipes.html