
:imagesdir: images

:docinfo:

= The Innovate Everywhere Recipe Book
:toc:

Welcome to the Innovate Everywhere Recipe Book!

Open Source contributors from around the globe have contributed recipes
to share some of the tastiest creations around. Within these virtual
pages find main (main course, for those outside the US), sides,
desserts, and drinks that will tantalize the tastebuds and impress your
friends! Innovation doesn't stop at dinner time, its time to bring open
source to your kitchen!
Have a lot of fun!

[id='sec.main']
== Main Courses

Main courses are the star of your meal, either stand alone or
complemented by a side dish.

ifdef::env-github[]
<<recipes/main/pasta_al_limone.adoc#, Pasta al limone>>
endif::[]
ifndef::env-github[]
include::recipes/main/pasta_al_limone.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/main/chicken-leek-pie.adoc#, Chicken and Leek Pie>>
endif::[]
ifndef::env-github[]
include::recipes/main/chicken-leek-pie.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/main/lentil_dal.adoc#, Lentil Dal>>
endif::[]
ifndef::env-github[]
include::recipes/main/lentil_dal.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/main/roulade_pretzel_dumplings.adoc#, Roulade with Pretzel Dumplings>>
endif::[]
ifndef::env-github[]
include::recipes/main/roulade_pretzel_dumplings.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/main/lasagne_bolognaise.adoc#, Lasagne Bolognaise>>
endif::[]
ifndef::env-github[]
include::recipes/main/lasagne_bolognaise.adoc[]
endif::[]

[id='sec.sides']
== Side Dishes

Side dishes complete a meal, providing a compliment to the entree like
the bass line in a song... essential components for a full experience.

ifdef::env-github[]
<<recipes/sides/raspberry_pretzel_salad.adoc#, Raspberry Pretzel Salad>>
endif::[]
ifndef::env-github[]
include::recipes/sides/raspberry_pretzel_salad.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/sides/vals_mac_cheese.adoc#, Val's Macaroni & Cheese>>
endif::[]
ifndef::env-github[]
include::recipes/sides/vals_mac_cheese.adoc[]
endif::[]


[id='sec.desserts']
== Desserts

Desserts bring a fanciful finsh to a proper meal, like the sunset after a
great day, dessert reminds us of the joy we experienced during our meal.

ifdef::env-github[]
<<recipes/desserts/caramel_apple_pie.adoc#, Caramel Apple Pie>>
endif::[]
ifndef::env-github[]
include::recipes/desserts/caramel_apple_pie.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/desserts/pink_stuff.adoc#, Pink Stuff>>
endif::[]
ifndef::env-github[]
include::recipes/desserts/pink_stuff.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/desserts/chocolate_muffins_with_liquid_core.adoc#, Chocolate Muffins With Liquid Core>>
endif::[]
ifndef::env-github[]
include::recipes/desserts/chocolate_muffins_with_liquid_core.adoc[]
endif::[]

ifdef::env-github[]
<<recipes/desserts/skubanky.adoc#, Škubánky>>
endif::[]
ifndef::env-github[]
include::recipes/desserts/skubanky.adoc[]
endif::[]


[id='sec.beverages']
== Beverages

The perfect beverage may accompany a meal or stand all on its own.
Perhaps a bit bubbly, or maybe a sweet fruit smoothie, beverages
cover the gamut of experiences from refreshing to stimulating.
