[id='sec.crazy_cake']

=== Crazy Cake

This is a Depression-era (1930s) chocolate cake recipe that is a favorite in my family.
Preheat oven to 350 degrees F, 180 degrees C

Combine in a mixing bowl:

* 2 cups sugar (380 g)
* 3 cups flour  (570 g)
* 1/3 cup cocoa (47 g)
* 2 tsp vinegar (10 ml)
* 1 tsp vanilla (5 ml)
* 1 tsp salt  (4.2 g)
* 3/4 cup oil (180 ml)
* 2 cup water (240 ml)
  
Mix all ingredients well, either with a mixer or by hand and pour into an ungreased pan.
Bake for 35-40 minutes

You can frost this with pretty much any icing, but Mom always used this recipe: 

Fudge Frosting

* 1/3 cup milk (80 ml)
* 1/4 tsp salt (4.2 g)
* 1 cup sugar (201 g)
* 1/4 cup shortening (50 g)
* 1 tsp vanilla (5 ml)
* 1 rounded tablespoon cocoa (use a soup spoon)

Mix all ingredients together except the vanilla in a saucepan and bring to a full rolling boil, stirring constantly, and boil 1 minute.
Add vanilla and beat until thick enough to spread. If it's too thick, add 1 tsp of cream and beat lightly. Spread while warm.
