[id='sec.skubanky']


=== Škubánky - A take on Czech potato poppy seed dumplings

This is variation of the Czech semolina potato dumplings with poppy
seeds. The original recipe does not include the additional cooking of
the dumplings and the poppy seeds are sprinkled onto the dumplings
once served. While more work, cooking the dumplings removes the raw
flour flavor and makes them easier to digest.

These are intended as a dessert, but they can be also eaten as a main
course.


Ingredients (serves 2 as a main course or 4 as a dessert):

* 500g peeled potatoes
* 175g semolina or any other flour
* poppy seeds (preferably ground ones)
* salt, sugar


Preparation:

1. Peel and cut the potatoes into small chunks, put them into salted
   water and bring to a boil. Measure the amount of water that you put
   into your pot, so that you can remove all but ~150ml.
2. Cook the potatoes for 10-12 min until fully cooked and soft.
3. Drain the water except for ~150ml and mash the potatoes.
4. Add the semolina or flour to the mashed potatoes and add a few
   tablespoons of sugar and poppy seeds to taste. If you serve this as
   a dessert, then you might want to add more sugar. If you don't have
   ground poppy seeds, then add more unground ones.
   Mix everything well until you get a sticky mass.
5. Bring at least 2l of water to a rolling boil in a big pot. Use two
   spoons to form dumplings and throw them into the boiling
   water. Take them out of the water once they start to surface and
   continue to cook the rest.
6. Enjoy immediately (they will start sticking together). Optionally
   you can serve these with a powdered sugar & poppy seed mixture and
   melted butter.
